variables:
  IMAGE_NAME: extwisnu/demo-app
  IMAGE_TAG: python-app-1.0

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt install make
  script:
    - make test

build_image: 
  stage: build 
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]

  variables: 
    DOCKER_HOST: tcp://docker:2375  # Gunakan 'docker' bukan 'localhost'
    DOCKER_TLS_CERTDIR: ""  # Nonaktifkan TLS (wajib)

  before_script:
    - export REGISTRY_USER="ext.wisnu@adastra.id"
    - export REGISTRY_PASS="Skills39s"
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
    

  script:
    - pwd
    - ls -lah
    - ls -lah src/app
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image: ubuntu
  script:
    - apt update
    - apt install sshpass -y
    - sshpass -p "Pnd77net!" ssh -t -o StrictHostKeyChecking=no root@10.10.12.108 "
        export REGISTRY_USER='ext.wisnu@adastra.id' &&
        export REGISTRY_PASS='Skills39s' &&
        echo \"\$REGISTRY_PASS\" | docker login -u \"\$REGISTRY_USER\" --password-stdin &&
        docker run -d -p 5000:5000 \$IMAGE_NAME:\$IMAGE_TAG"

    