variables:
  IMAGE_NAME: extwisnu/demo-app
  IMAGE_TAG: python-app-1.0

run_tests:
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt install make
  script:
    - make test

build_image:  
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
      command: ["--tls=false"]
  


  variables: 
    DOCKER_HOST: tcp://localhost:2375  # Gunakan localhost

  before_script:
    - sleep 10
    - export REGISTRY_USER="ext.wisnu@adastra.id"
    - export REGISTRY_PASS="Skills39s"
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t extwisnu/demo-app:python-app-1.0 .
    - docker push extwisnu/demo-app:python-app-1.0
